modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
A Create addon powered by Create and Create: Aeronautics.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.10,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="aeronautics_bundled"
    type="required"
    versionRange="[1.3.0,1.4.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[2.0.5,)"
    ordering="NONE"
    side="BOTH"
